#!/usr/bin/env bash

${JAVA_HOME}/bin/java \
    -cp ../build/libs/samples.jar \
    -XX:+UnlockDiagnosticVMOptions \
    -XX:GuaranteedSafepointInterval=300000 \
    -Dagrona.disable.bounds.checks=true \
    -Dreactor.aeron.sample.embeddedMediaDriver=true \
    -Dreactor.aeron.sample.exclusive.publications=true \
    ${JVM_OPTS} reactor.aeron.demo.pure.MdcPong
