#!/usr/bin/env bash

${JAVA_HOME}/bin/java \
    -cp ../build/libs/samples.jar \
    -XX:+UnlockDiagnosticVMOptions \
    -XX:GuaranteedSafepointInterval=300000 \
    -Daeron.sample.messages=1000000 \
    -Daeron.sample.embeddedMediaDriver=true \
    -Daeron.sample.request=8 \
    -Daeron.sample.messageLength=32 \
    -Dagrona.disable.bounds.checks=true \
    -Daeron.sample.exclusive.publications=true \
    ${JVM_OPTS} reactor.aeron.demo.raw.MdcPingNoWaitingWithSimpleBackpressure
